server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    path: /error
    include-exception: 'true'
  servlet:
    context-path: /
    encoding:
      charset: 'UTF-8'
      force-response: 'true'

spring:
  jackson:
    time-zone: UTC
  devtools:
    restart:
      enabled: false
  application:
    name: Blog
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    show-sql: ${SHOW_SQL}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    drop-first: ${LIQUIBASE_DROP_FIRST}
    change-log: ${LIQUIBASE_CHANGE_LOG}
    default-schema: public

security:
  config:
    jwtCookieName: ${SPRING_SECURITY_JWT_COOKIE_NAME}
    jwtSecret: ${SPRING_SECURITY_JWT_SECRET}
    jwtExpirationMs: ${SPRING_SECURITY_JWT_EXPIRATION_MS}

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_SEC}
    root: ${LOGGING_LEVEL_ROOT}
    ru.jordan.blog: ${LOGGING_LEVEL_BLOG}
  swagger-ui:
    docExpansion: none
